### ISSUE TITLE
OSError: Font generation failed

### ISSUE THREAD

**Issue by KingGamingYT** [dkosmari/System-Font-Replacer#1]
I'm trying to use the script and it works fine up until it attempts to save the font where it errors out in the fashion shown below. Any ideas?
![image](https://github.com/user-attachments/assets/455ece1a-8b91-4bb8-baae-c247b0a38bbc)

**Comment by dkosmari** [comment]
Make sure you have permissions to create files in the directory you're running the script from.
You can pass the full path to where you want to save the output, like `C:\users\something\Documents\CurseCasual+CafeStd.ttf`, as the last argument to the script.

**Comment by KingGamingYT** [comment]
That worked! When you mentioned that, my mind immediately shot to the fact I was using a non-admin powershell in a directory that required admin rights to modify and add files to, so that was almost definitely why. Thanks!
